# Generated by Django 5.2.16 on 2026-09-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationdocument',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('aadhaar', 'Aadhaar card'), ('bank_statement', 'Bank statement (last 3 months)'), ('document', 'Supporting document'), ('employment_contract', 'Current employment contract'), ('offer_letter', 'Offer / appointment letter'), ('passport', 'Passport'), ('payslip', 'Payslips (last 3 months)'), ('pf_statement', 'PF / EPF statement'), ('relieving_letter', 'Relieving / experience letter'), ('rental_agreement', 'Rental agreement'), ('utility_bill', 'Utility bill (electricity / water / gas)')], default='document', max_length=30),
        ),
    ]
