# Generated by Django 5.2.16 on 2026-09-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_verificationdocument_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='candidate_address',
            field=models.TextField(blank=True, help_text='Declared residential address, matched against the address proof document.'),
        ),
    ]
