# Generated by Django 5.2.16 on 2026-09-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_verificationrequest_candidate_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='candidate_education',
            field=models.TextField(blank=True, help_text='Declared education details, matched against the education documents.'),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='candidate_employment',
            field=models.TextField(blank=True, help_text='Declared employment history, matched against the employment documents.'),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='employment_is_fresher',
            field=models.BooleanField(default=False, help_text='Candidate declared no prior employment (fresher).'),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('aadhaar', 'Aadhaar card'), ('bank_statement', 'Bank statement (last 3 months)'), ('bonafide', 'Bonafide certificate'), ('degree_certificate', 'Degree certificate'), ('diploma', 'Diploma certificate'), ('document', 'Supporting document'), ('employment_contract', 'Current employment contract'), ('marksheet', 'Mark sheets / grade cards'), ('offer_letter', 'Offer / appointment letter'), ('passport', 'Passport'), ('payslip', 'Payslips (last 3 months)'), ('pf_statement', 'PF / EPF statement'), ('provisional_certificate', 'Provisional certificate'), ('relieving_letter', 'Relieving / experience letter'), ('rental_agreement', 'Rental agreement'), ('transcript', 'Official transcript'), ('utility_bill', 'Utility bill (electricity / water / gas)')], default='document', max_length=30),
        ),
    ]
