# Generated by Django 5.2.16 on 2026-09-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0004_verificationrequest_candidate_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='candidate_criminal',
            field=models.TextField(blank=True, help_text='Disclosed criminal cases, if any. Blank when the candidate declares a clean record.'),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='candidate_identity',
            field=models.TextField(blank=True, help_text='Declared identity details (name / DOB / ID number) as on the identity document.'),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='criminal_declares_clean',
            field=models.BooleanField(default=False, help_text='Candidate declares no pending/convicted criminal cases.'),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('aadhaar', 'Aadhaar card'), ('affidavit', 'Self-declaration affidavit'), ('bank_statement', 'Bank statement (last 3 months)'), ('bonafide', 'Bonafide certificate'), ('character_certificate', 'Character certificate'), ('degree_certificate', 'Degree certificate'), ('diploma', 'Diploma certificate'), ('document', 'Supporting document'), ('driving_license', 'Driving licence'), ('employment_contract', 'Current employment contract'), ('marksheet', 'Mark sheets / grade cards'), ('offer_letter', 'Offer / appointment letter'), ('pan_card', 'PAN card'), ('passport', 'Passport'), ('payslip', 'Payslips (last 3 months)'), ('pf_statement', 'PF / EPF statement'), ('police_clearance', 'Police clearance certificate'), ('provisional_certificate', 'Provisional certificate'), ('relieving_letter', 'Relieving / experience letter'), ('rental_agreement', 'Rental agreement'), ('transcript', 'Official transcript'), ('utility_bill', 'Utility bill (electricity / water / gas)'), ('voter_id', 'Voter ID')], default='document', max_length=30),
        ),
    ]
