# Generated by Django 5.2.16 on 2026-09-07 09:58

import django.db.models.deletion
import verification.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0005_verificationrequest_candidate_criminal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationdocument',
            name='source',
            field=models.CharField(choices=[('upload', 'Manual upload'), ('digilocker', 'DigiLocker')], default='upload', max_length=20),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='file',
            field=models.FileField(blank=True, upload_to=verification.models.document_upload_path),
        ),
        migrations.CreateModel(
            name='DigiLockerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digilocker_username', models.CharField(blank=True, max_length=100)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_demo', models.BooleanField(default=False, help_text='True when connected via the built-in demo simulator')),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digilocker_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DigiLockerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_key', models.CharField(help_text='DigiLocker doc type e.g. ADHCRD, PANCARD', max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('issued_date', models.CharField(blank=True, max_length=40)),
                ('uri', models.CharField(blank=True, help_text='DigiLocker document URI reference', max_length=500)),
                ('step_type', models.CharField(blank=True, help_text='Mapped BGV step type', max_length=30)),
                ('doc_type', models.CharField(blank=True, help_text='Mapped BGV doc_type', max_length=30)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='verification.digilockeraccount')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('account', 'doc_key')},
            },
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='digilocker_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='verification.digilockerdocument'),
        ),
    ]
