# Generated by Django 5.2.16 on 2026-09-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text='Support helpline number for calling', max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp number for messaging (digits with country code)', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('support_hours', models.CharField(blank=True, default='Mon - Sat, 9:00 AM - 7:00 PM', max_length=100)),
                ('is_call_enabled', models.BooleanField(default=True)),
                ('is_message_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
