# Generated by Django 5.2.16 on 2026-09-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_supportcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('internship', 'Internship'), ('remote', 'Remote'), ('walk-in', 'Walk-in')], max_length=20),
        ),
    ]
