# Generated by Django 5.2.16 on 2026-09-22 05:12

import core.models
import django.core.files.storage
import django.core.validators
import django.db.models.deletion
import pathlib
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_job_job_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_id',
            field=models.CharField(blank=True, help_text='Company registration ID (CIN / GSTIN / LLPIN)', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_id_document',
            field=models.FileField(blank=True, help_text='Corporate ID card / certificate of incorporation. PDF or image, max 5MB. Stored outside public media; only platform super admins can open it.', null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/user/job_portal/protected_media')), upload_to='company_ids/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), core.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='profile',
            name='trust_rejection_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='trust_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='trust_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_trust_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='trust_status',
            field=models.CharField(choices=[('unverified', 'Not Submitted'), ('pending', 'Pending Review'), ('verified', 'Trusted & Valid'), ('rejected', 'Rejected')], default='unverified', max_length=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='trust_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
