# Generated by Django 5.2.16 on 2026-09-22 07:34

import core.models
import django.core.files.storage
import django.core.validators
import django.db.models.deletion
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockInterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=12)),
                ('overall_score', models.PositiveIntegerField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mock_interview', to='core.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='MockInterviewAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('question', models.TextField()),
                ('kind', models.CharField(choices=[('skill', 'Skill Deep-dive'), ('technical', 'Technical'), ('experience', 'Experience'), ('behavioral', 'Behavioral')], max_length=12)),
                ('focus_keywords', models.JSONField(blank=True, default=list)),
                ('answer_text', models.TextField(blank=True, help_text='Typed answer or live speech-to-text transcript')),
                ('answer_audio', models.FileField(blank=True, help_text='Voice recording (webm/ogg/mp3/wav/m4a, max 10MB). Private storage.', null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/user/job_portal/protected_media')), upload_to='mock_interviews/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['webm', 'ogg', 'oga', 'mp3', 'wav', 'm4a']), core.models.validate_audio_size])),
                ('audio_duration_sec', models.FloatField(blank=True, null=True)),
                ('used_mic', models.BooleanField(default=False)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('matched_keywords', models.JSONField(blank=True, default=list)),
                ('missing_keywords', models.JSONField(blank=True, default=list)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.mockinterviewsession')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('session', 'order')},
            },
        ),
    ]
