# Generated by Django 5.2.16 on 2026-09-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mockinterviewsession_mockinterviewanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockinterviewsession',
            name='best_overall_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='current_attempt',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='history',
            field=models.JSONField(blank=True, default=list, help_text='Archived earlier attempts: [{attempt, overall_score, summary, completed_at}]'),
        ),
    ]
