# Generated by Django 5.2.16 on 2026-08-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_job_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='source',
            field=models.CharField(blank=True, choices=[('website', 'Company Website'), ('linkedin', 'LinkedIn'), ('other', 'Other')], default='website', help_text='Source where the candidate applied from', max_length=50),
        ),
    ]
