# Generated by Django 5.2.16 on 2026-09-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_jobapplication_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='whatsapp_opted_in',
            field=models.BooleanField(default=True),
        ),
    ]
