# Generated by Django 5.2.16 on 2026-09-18 04:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('role', models.CharField(blank=True, default='', max_length=120)),
                ('bio', models.TextField(blank=True, default='')),
                ('avatar_color', models.CharField(choices=[('red', '#dc2626'), ('purple', '#7c3aed'), ('teal', '#0d9488'), ('blue', '#2563eb'), ('amber', '#d97706'), ('pink', '#db2777')], default='red', max_length=12)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('interview-questions', 'Interview Questions'), ('career-guidance', 'Career Guidance'), ('job-application', 'Job Application'), ('resume-format', 'Resume Format'), ('salary', 'Salary Insights'), ('internships', 'Internships'), ('expert-edge', 'Expert Edge')], db_index=True, max_length=40)),
                ('excerpt', models.TextField(blank=True, default='', max_length=500)),
                ('content', models.TextField(help_text='Plain text markup: ## heading, ### subheading, - bullet, > quote, **bold**.')),
                ('tags', models.CharField(blank=True, default='', help_text='Comma separated tags.', max_length=300)),
                ('banner', models.CharField(choices=[('purple', 'linear-gradient(135deg, #a855f7 0%, #6d28d9 100%)'), ('blue', 'linear-gradient(135deg, #38bdf8 0%, #1d4ed8 100%)'), ('pink', 'linear-gradient(135deg, #f472b6 0%, #be185d 100%)'), ('teal', 'linear-gradient(135deg, #2dd4bf 0%, #0f766e 100%)'), ('amber', 'linear-gradient(135deg, #fbbf24 0%, #b45309 100%)'), ('green', 'linear-gradient(135deg, #4ade80 0%, #15803d 100%)'), ('slate', 'linear-gradient(135deg, #64748b 0%, #1e293b 100%)')], default='blue', max_length=12)),
                ('emoji', models.CharField(default='📝', max_length=8)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('published', models.BooleanField(db_index=True, default=True)),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogauthor')),
            ],
            options={
                'ordering': ['-published_at', '-id'],
            },
        ),
    ]
