# Generated by Django 5.2.16 on 2026-09-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='banner',
            field=models.CharField(choices=[('purple', 'Purple'), ('blue', 'Blue'), ('pink', 'Pink'), ('teal', 'Teal'), ('amber', 'Amber'), ('green', 'Green'), ('slate', 'Slate')], default='blue', max_length=12),
        ),
    ]
